name: opentofu-state-manager
services:
  api:
    container_name: opentofu-state-manager-api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: opentofu-state-manager-api:latest
    platform: linux/amd64
    environment:
      DEBUG: false
      PYTHONASYNCIODEBUG: true  # enable the AsyncIO debug mode, print a warning message when a task takes more than 100ms to execute
    ports:
      - "8080:8000"
    volumes:
      - ..:/app
    working_dir: /app
    command: gunicorn src.main:app --worker-class uvicorn.workers.UvicornWorker --reload --workers 1 -b 0.0.0.0:8000
    networks:
      - net

networks:
  net:
    driver: bridge
