"""add state versions

Revision ID: 46508283c198
Revises: 77c3995c8465
Create Date: 2025-03-19 14:44:27.350738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46508283c198'
down_revision = '77c3995c8465'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('operation_id', sa.String(length=255), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('states', 'operation_id')
    op.drop_column('states', 'storage_path')
    op.drop_column('states', 'state_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('state_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('states', sa.Column('storage_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('states', sa.Column('operation_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('state_versions')
    # ### end Alembic commands ### 
